name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Install cross
        run: cargo install cross

      - name: Build for Windows
        run: cross build --target x86_64-pc-windows-gnu --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: target/x86_64-pc-windows-gnu/release/*
