name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: target/debug/.fingerprint
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Install NASM
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm
          echo "NASM installed. Version: $(nasm -v)"

      - name: Set environment variable for NASM
        run: echo "ASM_NASM=$(which nasm)" >> $GITHUB_ENV

      - name: Install cross
        run: cargo install cross

      - name: Build for Windows
        run: cross build --target x86_64-pc-windows-gnu --release --jobs 4

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: target/x86_64-pc-windows-gnu/release/*
